const copy = {
  en: {
    demo: 'DEMO · sample content only',
    live: 'LIVE · authorized assets only',
    restart: 'Restart attendee',
    cancel: 'Cancel',
    confirm: 'Clear this attendee on this browser?',
    next: 'Next',
    retry: 'Try again',
    loading: 'Loading authorized assets…',
    welcome: 'Beauty is within\nall of us.',
    intro: 'With the right brands and technology, you can tell every unique story. See how Adobe and L’Oréal Groupe make it scale.',
    consent: 'I AGREE TO ALL OF THE ABOVE.',
    legal: 'Photo Release',
    closeRelease: 'Close photo release',
    releaseItems: [
      'I agree to participate in the photoshoot (the "Activity") and have my photo taken',
      'I grant permission for my photo to be edited and AI-transformed',
      {
        before: 'I consent to Adobe’s use of my photo to be displayed publicly (including on event screens at and during this event, online and through Adobe’s social media if you tag @AdobeFirefly) as detailed in the ',
        after: '.',
      },
      'I confirm that I am 18 years of age or older',
      {
        before: 'I understand that Adobe will use and protect any personal information about me in connection with the Activity and this registration in accordance with the ',
        linkText: 'Adobe Privacy Policy',
        url: 'https://www.adobe.com/privacy/policy.html',
        after: '.',
      },
      {
        before: 'I have read, understand, and agree to be bound by the terms of the ',
        after: ', which are incorporated into this consent by reference',
      },
    ],
    releaseTitle: 'PHOTO RELEASE',
    releaseBulletIntro: '',
    releaseParagraphs: [
      'By acknowledging and accepting this Release (“Release”), I irrevocably grant to Adobe, Inc. located at 345 Park Avenue, San Jose, California 95110 USA and any person, entity, or device photographing, filming, or recording Content (defined below) by any means during the photo session to be held at this marketing event (the “Event”)(the “Photo Session”), including Adobe’s licensees, successors, designees, and assigns (collectively “Adobe”), the right to photograph, create, record, license, and use still or motion photographs, illustration, animation, or other images taken of me and selected by me with Adobe software products, including AI modifications, that include my appearance, persona, and likeness (the “Content”) for the following purposes, (at Adobe’s discretion) : publication, distribution, display, and use on interactive screens located at and during the event, and in Adobe’s worldwide advertising, marketing, promotion, public relations, and social media channels (including posts featuring the L’Oreal Paris, L’Oreal Paris Professional, La Roche Posay, and YSL screens or related activation), in any media existing and known at the time the Content is used (the “Medias”). I agree that:',
      'Except for as provided herein, I agree that my personal information will not be made publicly available but may only be used in connection to licensing the Content where necessary (e.g., to defend claims and protect legal rights), and may be retained as long as necessary to fulfill this purpose, including by being shared with sub-licensees and assignees of Adobe and transferred to countries with differing data protection and privacy laws where it may be stored, accessed and used.',
      'I further agree that Adobe may collect and use my contact information, including my email address, for the purpose of delivering the Content to me and facilitating my participation in the Photo Session and the use, by Adobe, of the Content, and may communicate with me regarding the Content in accordance with Adobe’s privacy policies at www.adobe.com/fr/privacy/policy.html and the rights and releases granted under this Release.',
      'I understand that participation is not permitted for minors under this Release. I hereby confirm that I have reached the age of the majority in my country of residence.',
      'The rights granted herein are perpetual, worldwide, and royalty-free. For participants residing in France, the preceding provision is not applicable, and the following one applies instead: “the duration of the use of the Content by Adobe is 2 years from the date of the Photo Session”.',
      'I release, discharge, and agree to hold harmless Adobe and its licensees, sub-licensees, successors, designees, and assigns (“Released Parties”) from any liability arising out of or in connection with the use of the Content, including, without limitation, any and all claims for defamation or invasion of privacy or publicity. I acknowledge that the Released Parties are not responsible or liable for any unauthorized use or piracy of the Content.',
      'For participants residing in France, the following provision applies instead of the provisions regarding the Adobe’s limitation of liability set forth above: “In accordance with article l221-15 of the French consumer code, I acknowledge that Adobe may be relieved of all or part of its responsibility if it evidences that the breach or the improper performance of this release is related either to the participant or to the fact, unpredictable and insurmountable, of a third party to this release, or to a case of force majeure”.',
      'I represent and warrant that I am at least 18 years of age and have the full legal capacity to acknowledge and accept this Release on my own behalf. To the fullest extent permitted by the mandatory provisions of the applicable law, I acknowledge and agree that this Release is binding upon my heirs and assigns.',
      'The data controller is Adobe Inc. The data controller will process the personal data collected through the Photo Session for the purposes described in this Release. The legal basis for such a collection and processing is the following: “the data subject has given consent to the processing of his or her personal data for one or more specific purposes” (Article 1(a) of the Regulation (EU) 2016/679 General Data Protection Regulation).',
      'Adobe Inc. has implemented appropriate safeguards, including the execution of the European Commission’s Standard Contractual Clauses where required, with recipients of personal data located outside the European Union.',
      'For more information concerning the processing of your personal data, you may read Adobe’s privacy policies at www.adobe.com/fr/privacy/policy.html',
    ],
    releaseBullets: [
      'the Content may be used in combination with other images and may be modified, edited, combined with other content, and/or transformed using generative artificial (“AI”) intelligence or machine-learning technologies at my selection, including based on prompts or inputs selected by me or Adobe (with my approval) to create, generate, or develop computer AI-generated digital replicas, derivative, or synthetic outputs;',
      'the Content may be publicly displayed on screens, monitors, or projections at live events during the Event, activations, or exhibitions, including as mentioned above in high-visibility locations in the event and at live events during the Event, and distributed or displayed online Medias, including on social media platforms and may be viewed by a broad public audience;',
      'after participating in the generation of the Content, I have no right to inspect or approve the Content or the use to which the Content may be applied;',
      'Adobe is not obligated to publish, distribute, display or use the Content; and',
      'I am not entitled to any compensation and will not make claims associated with the Content, for any reason, to Adobe. ',
    ],
    start: 'Explore creative workflows',
    print: 'Print your L’Oréal ad',
    intakeBlocked: 'Lead capture is enabled but the approved Marketo integration is unavailable. Ask booth staff; submission cannot be bypassed.',
    portraits: 'Find your photo.',
    portraitsSub: 'Select your picture to begin your personalized L’Oréal experience.',
    empty: 'No authorized portraits are available yet. Ask the photographer or refresh.',
    name: 'Make it yours.',
    nameSub: 'Enter your name to personalize your experience.',
    nameLabel: 'Your name',
    namePlaceholder: 'Enter your name here',
    story: 'Your story with AI Coworker',
    coworkerHeading: 'Ask CX\nCoworker.',
    coworkerSub: "Don't hunt through endless project data that isn't relevant — for you, we have just the ticket.",
    exit: 'Exit the experience',
    connectCoworker: 'Connect hosted Coworker',
    coworkerAuthenticate: 'Authenticate Coworker in a new tab',
    coworkerRetry: 'Retry embedded Coworker',
    coworkerResetFailed: 'Coworker did not confirm that attendee data was cleared. Restart is incomplete; ask booth staff.',
    coworkerAuthHelp: 'Missing JWT after redirect? Authenticate in a new tab, return here, then retry. Embedded authentication requires the hosted session cookie to work in this browser; a successful tab login does not guarantee iframe access.',
    coworkerURL: 'Hosted Coworker URL with token (browser memory only; contacts the hosted app)',
    continued: 'Ask a Simulated Audience',
    unavailable: 'Hosted integration unavailable. Its runtime URL or enable flag is not configured.',
    demoStory: 'Demo story boundary: Coworker would use your name and selected portrait here. No external app is contacted.',
    demoContinued: 'Demo audience boundary: your selected ad would be sent to Coworker as a thumbnail.',
    graph: 'Explore Graph',
    openGraph: 'Open Graph in a new tab',
    returnGraph: 'I have returned from Graph',
    demoGraph: 'Demo Graph boundary. Use the return control to continue without an external application.',
    popup: 'The Graph tab was blocked. Allow pop-ups and try again.',
    pacing: 'Creative at the speed of now.',
    pacingSub: 'Experience interstitial only — this timer does not indicate Firefly progress or start generation.',
    ads: 'Tell your unique story.',
    adsSub: 'Select the ad you want to test with a simulated audience.',
    pending: 'Assets are pending. The independent workstation publishes them; this browser does not generate images.',
    partial: 'Some assets are available. All four ads are required before selection.',
    failed: 'Asset processing failed. Ask booth staff or refresh.',
    banners: 'Meeting every moment.',
    bannersSub: 'Your portrait across campaign formats.',
    demoBanners: 'Demo layout previews only — crops of the selected sample ad, not generated banner files.',
    bannerPending: 'Banner variations are not yet available.',
    endings: 'Print and QR sharing are unavailable in this shell. No print, download or QR has been created.',
    error: 'Unable to continue.',
    storage: 'Browser session storage is unavailable. Refresh-safe operation requires storage.',
    changed: 'This portrait or selected ad is no longer authorized. Restart or ask booth staff.',
    selected: 'Selected',
    refresh: 'Refresh assets',
  },
  fr: {
    demo: 'DÉMO · contenu exemple uniquement',
    live: 'DIRECT · contenus autorisés',
    restart: 'Recommencer',
    cancel: 'Annuler',
    confirm: 'Effacer cette session sur ce navigateur ?',
    next: 'Suivant',
    retry: 'Réessayer',
    loading: 'Chargement des contenus autorisés…',
    welcome: 'La beauté est en\nchacun de nous.',
    intro: 'Avec les marques et la technologie adaptée, chaque histoire prend vie de manière unique. Découvrez comment Adobe et le groupe L’Oréal donnent à la créativité une nouvelle dimension.',
    consent: 'JE SUIS D’ACCORD AVEC TOUT CE QUI PRÉCÈDE.',
    legal: 'Autorisation de droit à l’image',
    closeRelease: 'Fermer l’autorisation',
    releaseItems: [
      'J’accepte de participer à la séance photo (l’« Activité ») et de me faire prendre en photo',
      'J’accorde la permission que ma photo soit modifiée et transformée par l’IA',
      {
        before: 'Je consens à ce qu’Adobe utilise ma photo pour être affichée publiquement (y compris sur les écrans lors de cet événement, en ligne et sur les réseaux sociaux d’Adobe si vous identifiez @AdobeFirefly) comme détaillé dans ',
        after: '.',
      },
      'Je confirme que j’ai 18 ans ou plus',
      {
        before: 'Je comprends qu’Adobe utilisera et protégera toutes les informations personnelles me concernant en lien avec l’Activité et cette inscription conformément à la ',
        linkText: 'Politique de confidentialité d’Adobe',
        url: 'https://www.adobe.com/privacy/policy.html',
        after: '.',
      },
      {
        before: 'J’ai lu, compris et accepté d’être lié par les termes de l’',
        after: ', qui sont incorporés dans ce consentement par référence',
      },
    ],
    releaseTitle: 'Autorisation de droit à l’image',
    releaseBulletIntro: 'J’autorise ce qui suit :',
    releaseParagraphs: [
      'En acceptant la présente autorisation (« l’Autorisation »), j’accorde à Adobe, dont le siège est situé au 345 Park Avenue, San Jose, California 95110 Etats-Unis, ainsi qu’à toute personne, entité réalisant des photographies, captations ou enregistrements du Contenu (tel que défini ci-dessous) par quelque moyen que ce soit, dans le cadre de la séance photo (la « Séance Photo ») organisée lors de cet événement marketing (l’«Événement»), y compris aux licenciés, successeurs, représentants et ayants droit d’Adobe (collectivement dénommés « Adobe »), le droit de photographier, créer, enregistrer, concéder sous licence et utiliser des photographies fixes ou animées, illustrations, animations ou autres images me représentant et sélectionnées par moi à l’aide des logiciels de Adobe, y compris avec des modifications réalisées par intelligence artificielle, intégrant mon image (le « Contenu »), aux fins suivantes, (à la discrétion d’Adobe) : publication, diffusion, affichage et utilisation sur des écrans interactifs situés à cet événement, ainsi que dans les campagnes publicitaires, marketing, promotionnelles, de relations publiques et sur les réseaux sociaux d’Adobe dans le monde entier (y compris les publications intégrant les écrans de L’Oreal Paris, L’Oreal Paris Professional, La Roche Posay, and YSL ou les activations associées), sur tout support existant ou connu au moment de l’utilisation du Contenu (les « Supports»).',
      'Sauf disposition contraire prévue aux présentes, j’accepte que mes données personnelles ne soient pas rendues publiques, mais puissent être utilisées uniquement dans le cadre de l’exploitation et de la concession de licences relatives au Contenu lorsque cela est nécessaire (par exemple pour défendre des droits ou répondre à des réclamations juridiques). Ces données pourront être conservées aussi longtemps que nécessaire à cette fin, y compris être communiquées aux sous-licenciés et ayants droit d’Adobe et transférées vers des pays dont la législation en matière de protection des données et de la vie privée diffère, où elles pourront être stockées, consultées et utilisées.',
      'J’accepte également qu’Adobe collecte et utilise mes coordonnées, y compris mon adresse électronique, afin de me transmettre le Contenu, de faciliter ma participation à la Séance Photo et l’utilisation du Contenu par Adobe, et puisse communiquer avec moi au sujet du Contenu conformément à la politique de confidentialité de Adobe disponible à l’adresse www.adobe.com/fr/privacy/policy.html ainsi qu’aux droits et autorisations accordés par la présente Autorisation.',
      'Je comprends que cette Autorisation ne s’applique pas aux mineurs, qui ne sont pas autorisés à participer. Je confirme par la présente avoir atteint l’âge de la majorité dans mon pays de résidence.',
      'Les droits accordés aux présentes sont perpétuels, mondiaux et exempts de redevances. Toutefois, pour les participants résidant en France, cette disposition ne s’applique pas et est remplacée par la suivante : « La durée d’utilisation du Contenu par Adobe est fixée à deux (2) ans à compter de la date de la Séance Photo ».',
      'Je décharge Adobe ainsi que ses licenciés, sous-licenciés, successeurs, représentants et ayants droit (les « Parties Bénéficiaires de l’Autorisation ») de toute responsabilité découlant de l’utilisation du Contenu ou liée à celle-ci, y compris, sans limitation, toute réclamation fondée sur la diffamation, l’atteinte à la vie privée ou au droit à l’image. Je reconnais que les Parties Bénéficiaires de l’Autorisation ne peuvent être tenues responsables de toute utilisation non autorisée ou de tout acte de piratage concernant le Contenu.',
      'Pour les participants résidant en France, la disposition suivante remplace les clauses ci-dessus relatives à la limitation de responsabilité d’Adobe :',
      '« Conformément à l’article L.221-15 du Code de la consommation, je reconnais qu’Adobe peut être exonérée de tout ou partie de sa responsabilité si elle démontre que l’inexécution ou la mauvaise exécution de la présente Autorisation est imputable soit au participant, soit au fait imprévisible et insurmontable d’un tiers au contrat, soit à un cas de force majeure. »',
      'Je déclare et garantis être âgé(e) d’au moins 18 ans et disposer de la pleine capacité juridique nécessaire pour prendre connaissance et accepter la présente Autorisation en mon nom propre. Dans toute la mesure permise par les dispositions impératives du droit applicable, je reconnais et accepte que la présente Autorisation lie également mes héritiers et ayants droit.',
      'Le responsable du traitement des données est Adobe Inc. Celui-ci traitera les données personnelles collectées dans le cadre de la Séance Photo aux fins décrites dans la présente Autorisation. Les données collectées sont traitées pour les finalités suivantes :',
      '« La personne concernée a consenti au traitement de ses données à caractère personnel pour une ou plusieurs finalités spécifiques » (article 6, paragraphe 1, point a), du Règlement (UE) 2016/679 relatif à la protection des données – RGPD).',
      'Adobe, Inc. a mis en œuvre les garanties appropriées, notamment la conclusion des Clauses Contractuelles Types de la Commission européenne lorsque cela est requis, avec les destinataires des données personnelles situés en dehors de l’Union européenne.',
      'Cannes Lions Autorisation Juin 2026',
      'Pour davantage d’informations concernant le traitement de vos données personnelles, vous pouvez consulter la politique de confidentialité d’Adobe à l’adresse www.adobe.com/fr/privacy/policy.html',
    ],
    releaseBullets: [
      'Le Contenu peut être utilisé en combinaison avec d’autres images et peut être modifié, édité, combiné avec d’autres contenus et/ou transformé au moyen de technologies d’intelligence artificielle générative (« IA ») ou d’apprentissage automatique, selon mes choix, notamment à partir d’instructions (« prompts ») ou de données sélectionnées par moi-même ou par Adobe (avec mon approbation), afin de créer, générer ou développer des répliques numériques générées par IA, des œuvres dérivées ou des contenus synthétiques ;',
      'Le Contenu peut être diffusé publiquement sur des écrans, moniteurs ou dispositifs de projection lors d’événements en direct organisés dans le cadre de l’Événement, d’animations promotionnelles ou d’expositions, y compris, comme indiqué ci-dessus, dans des lieux à forte visibilité à cet événement, et peut être diffusé ou rendu accessible en ligne sur des médias numériques, y compris sur les plateformes de réseaux sociaux, et être ainsi consulté par un large public. Après avoir participé à la création du Contenu, je ne dispose d’aucun droit d’inspection ou d’approbation du Contenu ni des usages qui pourront en être faits ;',
      'Adobe n’est pas tenue de publier, diffuser, afficher ou utiliser le Contenu ;',
      'Je ne suis en droit de percevoir aucune rémunération et je m’engage à ne présenter aucune réclamation à Adobe concernant le Contenu, pour quelque motif que ce soit.',
    ],
    start: 'Explorer les workflows créatifs',
    print: 'Imprimer votre publicité L’Oréal',
    intakeBlocked: 'La collecte est activée mais l’intégration Marketo approuvée est indisponible. Contactez l’équipe du stand ; aucun contournement n’est possible.',
    portraits: 'Choisissez votre photo.',
    portraitsSub: 'Sélectionnez votre image pour commencer votre expérience L’Oréal personnalisée.',
    empty: 'Aucun portrait autorisé disponible. Contactez le photographe ou actualisez.',
    name: 'À votre image.',
    nameSub: 'Saisissez votre nom pour personnaliser votre expérience.',
    nameLabel: 'Votre nom',
    namePlaceholder: 'Saisissez votre nom ici',
    story: 'Votre histoire avec AI Coworker',
    coworkerHeading: 'Demandez à CX\nCoworker.',
    coworkerSub: 'Ne cherchez plus parmi des données de projet sans pertinence : nous avons ce qu’il vous faut.',
    exit: 'Quitter l’expérience',
    connectCoworker: 'Connecter Coworker hébergé',
    coworkerAuthenticate: 'Authentifier Coworker dans un nouvel onglet',
    coworkerRetry: 'Réessayer Coworker intégré',
    coworkerResetFailed: 'Coworker n’a pas confirmé l’effacement des données. Le redémarrage est incomplet ; contactez l’équipe du stand.',
    coworkerAuthHelp: 'Jeton JWT absent après redirection ? Authentifiez-vous dans un nouvel onglet, revenez ici, puis réessayez. Le cookie de session doit fonctionner dans ce navigateur ; une connexion réussie dans un onglet ne garantit pas l’accès intégré.',
    coworkerURL: 'URL Coworker avec jeton (mémoire du navigateur uniquement ; contacte l’application hébergée)',
    continued: 'Demander à une audience simulée',
    unavailable: 'Intégration hébergée indisponible. Son URL ou son activation n’est pas configurée.',
    demoStory: 'Étape de démonstration : Coworker utiliserait votre nom et votre portrait. Aucune application externe n’est contactée.',
    demoContinued: 'Étape de démonstration : la publicité sélectionnée serait envoyée à Coworker sous forme de miniature.',
    graph: 'Découvrir Graph',
    openGraph: 'Ouvrir Graph dans un nouvel onglet',
    returnGraph: 'Je suis de retour de Graph',
    demoGraph: 'Étape Graph de démonstration. Revenez pour continuer sans application externe.',
    popup: 'L’onglet Graph a été bloqué. Autorisez les fenêtres et réessayez.',
    pacing: 'Votre création en un instant.',
    pacingSub: 'Interlude uniquement — ce délai ne représente pas la progression de Firefly et ne lance aucune génération.',
    ads: 'Racontez votre propre histoire.',
    adsSub: 'Sélectionnez la campagne à tester avec une audience simulée.',
    pending: 'Contenus en attente. Le poste indépendant les publie ; ce navigateur ne génère aucune image.',
    partial: 'Certains contenus sont disponibles. Les quatre publicités sont requises avant sélection.',
    failed: 'Le traitement a échoué. Contactez l’équipe du stand ou actualisez.',
    banners: 'Saisir chaque instant.',
    bannersSub: 'Votre portrait dans différents formats de campagne.',
    demoBanners: 'Aperçus de mise en page uniquement — recadrages de l’exemple choisi, pas des bannières générées.',
    bannerPending: 'Les bannières ne sont pas encore disponibles.',
    endings: 'Impression et partage QR indisponibles. Aucun fichier, QR ou tirage n’a été créé.',
    error: 'Impossible de continuer.',
    storage: 'Le stockage de session du navigateur est indisponible. Il est requis pour reprendre après actualisation.',
    changed: 'Ce portrait ou cette publicité n’est plus autorisé. Recommencez ou contactez l’équipe.',
    selected: 'Sélectionné',
    refresh: 'Actualiser les contenus',
  },
};

export default copy;
